/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'H129273' at '22/02/17 14:36' with Gradle 2.13
 *
 * @author H129273, @date 22/02/17 14:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
